version: "3.8"

services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform-cli
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
